name: Auto-close PRs
on:
  pull_request_target:
    types: [opened, reopened]

jobs:
  close-pr:
    runs-on: ubuntu-latest
    # Closes the PR if the author is NOT an Owner or Member of the repository/org
    if: |
      github.event.pull_request.author_association != 'OWNER' && 
      github.event.pull_request.author_association != 'MEMBER'
    permissions:
      pull-requests: write 
    steps:
      - name: Close PR
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Thank you for your interest! However, this project does not accept external Pull Requests. This PR has been closed automatically."
